### ISSUE TITLE
Works with Rust 1.43

### ISSUE THREAD

**Issue by hcsch** [lifthrasiir/hexf#18]
I just checked if hexf 0.2.1 can compile with Rust 1.43 and it seems to work just fine. Was there any particular reason for the MSRV of 1.45? If possible I'd appreciate it if the MSRV could be lowered to 1.43 (at least for versions 0.2.x), as this would allow me to use hexf-parse for gfx-rs/naga#1184.

**Comment by youknowone** [comment]
That change came from #9, so I just thought its minimal requirement was 1.45. I don't think there was concrete background to decide it. Would you make a PR to change README and CI configuraiton to change the rust version?

**Comment by hcsch** [comment]
Sure, thanks for being open to this ^^
